src/sk4rbonka/main/default/objects/sk4_cumulation__c/sk4_cumulation__c.object-meta.xml
<CustomObject>
    <label>Cumulation</label>
    <nameField>
        <displayFormat>CML-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cumulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_cumulationMonth__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationMonth__c</fullName>
    <formula>MONTH(sk4_cumulationDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cumulation Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_cumulationYear__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationYear__c</fullName>
    <formula>YEAR(sk4_cumulationDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cumulation Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Cumulations</relationshipLabel>
    <relationshipName>Cumulations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/classes/SOQL/SOQL_Cumulation.cls
public with sharing class SOQL_Cumulation extends SOQL implements SOQL.Selector {
    public static SOQL_Cumulation query() {
        return new SOQL_Cumulation();
    }

    private SOQL_Cumulation() {
        super(sk4_cumulation__c.SObjectType);
        with(
                new List<SObjectField>{
                    sk4_cumulation__c.Id,
                    sk4_cumulation__c.sk4_family__c,
                    sk4_cumulation__c.sk4_cumulationMonth__c,
                    sk4_cumulation__c.sk4_cumulationYear__c
                }
            )
            .systemMode()
            .withSharing();
    }
}