src/sk4rbonka/main/default/objects/sk4_cumulation__c/sk4_cumulation__c.object-meta.xml
<CustomObject>
    <label>Cumulation</label>
    <nameField>
        <displayFormat>CML-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cumulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_cumulationDate__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationDate__c</fullName>
    <label>Cumulation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Cumulations</relationshipLabel>
    <relationshipName>Cumulations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationDay__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationDay__c</fullName>
    <label>Cumulation Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationPercent__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationPercent__c</fullName>
    <label>Cumulation Percent</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/schedule/main/default/classes/sk4_CumulateBatch.cls
public with sharing class sk4_CumulateBatch implements Database.Batchable<sObject> {
    
    private Boolean hasCumulationToday(Decimal cumulationDay) {
        Date today = Date.today();
        Integer numberOfDays = Date.daysInMonth(today.year(), today.month());
        if (numberOfDays < cumulationDay) {
            return today.day() == numberOfDays;
        }
        return cumulationDay == today.day();
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query ='SELECT Id, sk4_cumulationDay__c FROM sk4_family__c WHERE ';
        query += '(sk4_cumulationPercent__c != NULL AND sk4_cumulationDay__c != NULL)';
        return Database.getQueryLocator(query);
     }
  
     public void execute(Database.BatchableContext BC, List<sk4_family__c> scope){
        List<sk4_cumulation__c> cumuls = new List<sk4_cumulation__c>();
        for (sk4_family__c family: scope) {
            if (hasCumulationToday(family.sk4_cumulationDay__c)) {
                sk4_cumulation__c cumul = new sk4_cumulation__c();
                cumul.sk4_family__c = family.Id;
                cumul.sk4_cumulationDate__c = date.today();
                cumuls.add(cumul);

            }
        }

        insert cumuls;       

     }
  
     public void finish(Database.BatchableContext BC){
     }
}