src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/sk4_parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Parents</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_user__c.field-meta.xml
<CustomField>
    <fullName>sk4_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>sk4_parents</relationshipName>
    <type>Lookup</type>
</CustomField>

src/soql/main/default/classes/SOQL_Parent.cls
public with sharing class SOQL_Parent extends SOQL implements SOQL.Selector {
    public static SOQL_Parent query() {
        return new SOQL_Parent();
    }

    private SOQL_Parent() {
        super(sk4_parent__c.SObjectType);
        with(new List<SObjectField>{ sk4_parent__c.Id, sk4_parent__c.sk4_family__c }).systemMode().withoutSharing();
    }

    public SOQL_Parent byCurrentUser() {
        whereAre(Filter.with(sk4_parent__c.sk4_user__c).equal(UserInfo.getUserId()));
        return this;
    }
}