src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/sk4_parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Parents</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_user__c.field-meta.xml
<CustomField>
    <fullName>sk4_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>sk4_parents</relationshipName>
    <type>Lookup</type>
</CustomField>

src/soql/main/default/classes/SOQL_ParentTest.cls
@IsTest
public with sharing class SOQL_ParentTest {
    @TestSetup
    static void makeData() {
        User user1 = sk4_TestDataFactory.createSk4rbonkaUser('John');
        User user2 = sk4_TestDataFactory.createSk4rbonkaUser('Jane');

        sk4_family__c family = sk4_TestDataFactory.createFamilies('Doe', 1)[0];
        insert family;

        sk4_parent__c parent1 = sk4_TestDataFactory.createParent('John', family.Id);
        sk4_parent__c parent2 = sk4_TestDataFactory.createParent('Jane', family.Id);
        parent1.sk4_user__c = user1.Id;
        parent2.sk4_user__c = user2.Id;
        insert new List<sk4_parent__c>{ parent1, parent2 };
    }

    @IsTest
    static void testGetByCurrentUser() {
        User u = [SELECT Id FROM User WHERE LastName = 'John'];
        System.runAs(u) {
            Test.startTest();
            sk4_parent__c parent = (sk4_parent__c) SOQL_Parent.query()
                .byCurrentUser()
                .with(sk4_parent__c.Name)
                .toObject();
            Test.stopTest();

            Assert.areEqual('John', parent.Name);
        }
    }
}