src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationDay__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationDay__c</fullName>
    <label>Cumulation Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationPercent__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationPercent__c</fullName>
    <label>Cumulation Percent</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultPocketMoneyAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultPocketMoneyAmount__c</fullName>
    <label>Default PocketMoney Amount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/classes/sk4_FamilyController.cls
@RestResource(urlMapping = '/Family/*')
global with sharing class sk4_FamilyController {
    @HttpGet
    global static List<sk4_family__c> doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        List<sk4_family__c> families = [SELECT Id, Name, sk4_cumulationDay__c, sk4_cumulationPercent__c, sk4_defaultPocketMoneyAmount__c
                                        FROM sk4_family__c];
        return families;
    }

}