src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_balance__c.field-meta.xml
<CustomField>
    <fullName>sk4_balance__c</fullName>
    <formula>sk4_savingsSum__c - sk4_withdrawsSum__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_fullName__c.field-meta.xml
<CustomField>
    <fullName>sk4_fullName__c</fullName>
    <formula>Name + &apos; &apos; +  sk4_family__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultPocketMoneyAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultPocketMoneyAmount__c</fullName>
    <label>Default PocketMoney Amount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_parent__c/sk4_parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Parents</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_user__c.field-meta.xml
<CustomField>
    <fullName>sk4_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>sk4_parents</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_parent__c.field-meta.xml
<CustomField>
    <fullName>sk4_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/classes/sk4_Wholesale.cls
public with sharing class sk4_Wholesale {
    @AuraEnabled
    public static List<ChildWrapper> getAllChildren() {
        List<ChildWrapper> wrappers = new List<ChildWrapper>();
        for (sk4_child__c child : [
            SELECT Id, sk4_fullName__c, sk4_balance__c, sk4_family__r.sk4_defaultPocketMoneyAmount__c
            FROM sk4_child__c
        ]) {
            ChildWrapper cw = new ChildWrapper();
            cw.fullName = child.sk4_fullName__c;
            cw.balance = child.sk4_balance__c;
            cw.defaultAmount = child.sk4_family__r.sk4_defaultPocketMoneyAmount__c;
            cw.id = child.Id;
            wrappers.add(cw);
        }

        return wrappers;
    }

    @AuraEnabled
    public static void saveNewTransfers(List<ChildWrapper> children) {
        sk4_parent__c parent = [
            SELECT Id, sk4_family__c
            FROM sk4_parent__c
            WHERE sk4_user__c = :UserInfo.getUserId()
        ];

        List<sk4_transfer__c> transfers = new List<sk4_transfer__c>();

        for (ChildWrapper child : children) {
            if (child.give != null && child.give > 0) {
                sk4_CreateTransferRecords.Parameters p = new sk4_CreateTransferRecords.Parameters();
                p.type = sk4_Const.TRANSFER_TYPE_POCKETMONEY;
                p.parentId = parent.Id;
                p.familyId = parent.sk4_family__c;
                p.childId = child.Id;
                p.transferAmount = child.give;
                transfers.add(sk4_CreateTransferRecords.createTransfer(p));
            }
        }

        sk4_CreateTransferRecords.insertRecords(transfers);
    }

    public class ChildWrapper {
        @AuraEnabled
        public Id id { get; set; }
        @AuraEnabled
        public Decimal give { get; set; }
        @AuraEnabled
        public String fullName { get; set; }
        @AuraEnabled
        public Decimal balance { get; set; }
        @AuraEnabled
        public Decimal defaultAmount { get; set; }
    }
}