src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_balance2__c.field-meta.xml
<CustomField>
    <fullName>sk4_balance2__c</fullName>
    <label>Balance</label>
    <summarizedField>sk4_transfer__c.sk4_transferAmount__c</summarizedField>
    <summaryForeignKey>sk4_transfer__c.sk4_child__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_fullName__c.field-meta.xml
<CustomField>
    <fullName>sk4_fullName__c</fullName>
    <formula>Name + &apos; &apos; +  sk4_family__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultParent__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultParent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sk4_parent__c.sk4_family__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Families</relationshipLabel>
    <relationshipName>Families</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/classes/SOQL/SOQL_Child.cls
public with sharing class SOQL_Child extends SOQL implements SOQL.Selector {
    public static SOQL_Child query() {
        return new SOQL_Child();
    }

    private SOQL_Child() {
        super(sk4_child__c.SObjectType);
        with(new List<SObjectField>{ sk4_child__c.Id, sk4_child__c.Name, sk4_child__c.sk4_balance2__c, sk4_child__c.sk4_fullName__c });
        with('sk4_family__r', sk4_family__c.sk4_defaultParent__c);
        systemMode();
        withSharing();
    }

    public SOQL_Child byFamilyIds(Set<Id> familyIds) {
        whereAre(Filter.with(sk4_child__c.sk4_family__c).isIn(familyIds));
        return this;
    }

}