src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_balance__c.field-meta.xml
<CustomField>
    <fullName>sk4_balance__c</fullName>
    <formula>sk4_savingsSum__c - sk4_withdrawsSum__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/sk4_cumulation__c.object-meta.xml
<CustomObject>
    <label>Cumulation</label>
    <nameField>
        <displayFormat>CML-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cumulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_cumulation__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cumulation</label>
    <referenceTo>sk4_cumulation__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/recordTypes/Cumulation.recordType-meta.xml
<RecordType>
    <fullName>Cumulation</fullName>
    <active>true</active>
    <label>Cumulation</label>
</RecordType>

src/sk4rbonka/classes/sk4_Cumulate.cls
public class sk4_Cumulate {
    private static final String CUMULATION_TRANSFER = 'Cumulation';
    public class FlowInput {
        @InvocableVariable(label = 'List of children'required = true)
        public List<sk4_child__c> children;
        @InvocableVariable(label = 'Percent'required = true)
        public Decimal percent;
    }

    @InvocableMethod
    public static void doCumulate(List<FlowInput> inputs) {
        List<sk4_transfer__c> transfers = new List<sk4_transfer__c>();
        Id cumulationId = createCumulation();
        for (sk4_child__c child : inputs[0].children) {
            Decimal transferAmount = child.sk4_balance__c * inputs[0].percent / 100;
            transfers.add(sk4_CreateTransferRecords.createTransfer(CUMULATION_TRANSFER, child.Id, transferAmount, cumulationId));
        }

        sk4_CreateTransferRecords.insertRecords(transfers);
    }


    private static Id createCumulation() {
        sk4_cumulation__c cumulation = new sk4_cumulation__c();
        insert cumulation;
        return cumulation.Id;
    }
}