src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/classes/SOQL/SOQL_ChildTest.cls
@IsTest
public with sharing class SOQL_ChildTest {
    @TestSetup
    static void makeData() {
        List<sk4_family__c> families = sk4_TestDataFactory.createFamilies('Nowak', 3);
        insert families;

        List<sk4_child__c> children = sk4_TestDataFactory.createChildren('Jan', 2, families[0].Id);
        children.addAll(sk4_TestDataFactory.createChildren('Maria', 2, families[1].Id));
        insert children;
    }

    @IsTest
    static void testQuery() {
        Test.startTest();
        List<SObject> children = SOQL_Child.query().toList();
        Test.stopTest();

        Assert.areEqual(4, children.size());
    }

    @IsTest
    static void testByFamilyIds() {
        Set<Id> familyIds = new Map<Id, sk4_family__c>([SELECT Id FROM sk4_family__c WHERE Name = 'Nowak1']).keyset();

        Test.startTest();
        List<sObject> children = SOQL_Child.query().byFamilyIds(familyIds).toList();
        Test.stopTest();

        Assert.areEqual(2, children.size());
    }
}