src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_date__c.field-meta.xml
<CustomField>
    <fullName>sk4_date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_description__c.field-meta.xml
<CustomField>
    <fullName>sk4_description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_transferAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_transferAmount__c</fullName>
    <label>Transfer Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_type__c.field-meta.xml
<CustomField>
    <fullName>sk4_type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PocketMoney</fullName>
            </value>
            <value>
                <fullName>Cumulation</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sk4rbonka/main/default/classes/sk4_TransferController.cls
public with sharing class sk4_TransferController {
    private static final List<String> transfersToQuery = new List<String>{
        sk4_Const.TRANSFER_TYPE_POCKETMONEY,
        sk4_Const.TRANSFER_TYPE_WITHDRAW,
        sk4_Const.TRANSFER_TYPE_CUMULATION,
        sk4_Const.TRANSFER_TYPE_OTHER,
        sk4_Const.TRANSFER_TYPE_DEDUCTION
    };

    @AuraEnabled
    public static List<String> getMinusTypes() {
        return sk4_Const.MINUS_TRANSFERS;
    }

    @AuraEnabled
    public static List<Wrapper> getTransfersByChildren(Id childId) {
        List<Wrapper> result = new List<Wrapper>();

        List<sk4_transfer__c> transfers = [
            SELECT Id, sk4_date__c, sk4_description__c, sk4_type__c, sk4_transferAmount__c
            FROM sk4_transfer__c
            WHERE sk4_child__c = :childId AND sk4_type__c IN :transfersToQuery
            ORDER BY sk4_date__c ASC
        ];

        Integer l = transfers.size();
        List<Wrapper> wrappers = new List<Wrapper>();

        for (Integer i = 0; i < l; i++) {
            if (i == 0) {
                wrappers.add(new Wrapper(transfers[i], 0));
            } else {
                Decimal total = wrappers[i - 1].total;
                wrappers.add(new Wrapper(transfers[i], total));
            }
        }

        return wrappers;
    }

    public class Wrapper {
        @AuraEnabled
        public Id id;
        @AuraEnabled
        public Date dt;
        @AuraEnabled
        public String description;
        @AuraEnabled
        public Decimal amount;
        @AuraEnabled
        public String type;
        @AuraEnabled
        public Decimal total;
        public Wrapper(sk4_transfer__c transfer, Decimal total) {
            this.id = transfer.Id;
            this.dt = Date.valueOf(transfer.sk4_date__c);
            this.description = transfer.sk4_description__c;
            this.amount = transfer.sk4_transferAmount__c;
            this.type = transfer.sk4_type__c;

            if (sk4_Const.PLUS_TRANSFERS.contains(this.type)) {
                this.total = total + this.amount;
            } else if (sk4_Const.MINUS_TRANSFERS.contains(this.type)) {
                this.total = total - this.amount;
            }
        }
    }
}