src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/sk4_cumulation__c.object-meta.xml
<CustomObject>
    <label>Cumulation</label>
    <nameField>
        <displayFormat>CML-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cumulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_cumulationDate__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationDate__c</fullName>
    <label>Cumulation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Cumulations</relationshipLabel>
    <relationshipName>Cumulations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationDay__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationDay__c</fullName>
    <label>Cumulation Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_CumulationEnabled__c.field-meta.xml
<CustomField>
    <fullName>sk4_CumulationEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cumulation Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultParent__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultParent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sk4_parent__c.sk4_family__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Families</relationshipLabel>
    <relationshipName>Families</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultPocketMoneyAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultPocketMoneyAmount__c</fullName>
    <label>Default PocketMoney Amount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_PocketMoneyDay__c.field-meta.xml
<CustomField>
    <fullName>sk4_PocketMoneyDay__c</fullName>
    <label>PocketMoney Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_ScheduledPocketMoneyEnabled__c.field-meta.xml
<CustomField>
    <fullName>sk4_ScheduledPocketMoneyEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scheduled PocketMoney Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_cumulation__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cumulation</label>
    <referenceTo>sk4_cumulation__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/schedule/main/default/classes/sk4_ScheduleBatch.cls
public with sharing class sk4_ScheduleBatch implements Database.Batchable<sObject> {
    private Boolean isTransferDay(Decimal todaysDay) {
        Date today = Date.today();
        Integer numberOfDays = Date.daysInMonth(today.year(), today.month());
        if (numberOfDays < todaysDay) {
            return today.day() == numberOfDays;
        }
        return todaysDay == today.day();
    }

    private sk4_cumulation__c createCumulation(sk4_family__c family){
        sk4_cumulation__c cumul = new sk4_cumulation__c();
        cumul.sk4_family__c = family.Id;
        cumul.sk4_cumulationDate__c = date.today();
        return cumul;
    }

    private List<sk4_transfer__c> createPocketMoneyTransfers(sk4_family__c family) {
        List<sk4_transfer__c> transfers = new List<sk4_transfer__c>();
        for (sk4_child__c child : family.Children__r) {
            transfers.add(sk4_CreateTransferRecords.createPocketMoneyTransfer(family, child.Id));
        }
        return transfers;
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = '';
        query += 'SELECT Id,  sk4_cumulationDay__c, sk4_PocketMoneyDay__c, sk4_defaultPocketMoneyAmount__c,';
        query += 'sk4_defaultParent__c, sk4_ScheduledPocketMoneyEnabled__c , sk4_CumulationEnabled__c, ';
        query += '(SELECT Id FROM Children__r) ';
        query += 'FROM sk4_family__c ';
        query += 'WHERE (sk4_ScheduledPocketMoneyEnabled__c = TRUE OR sk4_CumulationEnabled__c = TRUE)';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sk4_family__c> scope) {
        List<sk4_cumulation__c> cumuls = new List<sk4_cumulation__c>();
        List<sk4_transfer__c> pocketMoneys = new List<sk4_transfer__c>();
        for (sk4_family__c family : scope) {
            if (family.sk4_ScheduledPocketMoneyEnabled__c && isTransferDay(family.sk4_PocketMoneyDay__c)) {
                pocketMoneys.addAll(createPocketMoneyTransfers(family));
            }
            if (family.sk4_CumulationEnabled__c && isTransferDay(family.sk4_cumulationDay__c)) {
                cumuls.add(createCumulation(family));
            }
        }

        insert cumuls;
        insert pocketMoneys;
    }

    public void finish(Database.BatchableContext BC) {
    }

}