src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/sk4_cumulation__c.object-meta.xml
<CustomObject>
    <label>Cumulation</label>
    <nameField>
        <displayFormat>CML-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cumulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Cumulations</relationshipLabel>
    <relationshipName>Cumulations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationDay__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationDay__c</fullName>
    <label>Cumulation Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_CumulationEnabled__c.field-meta.xml
<CustomField>
    <fullName>sk4_CumulationEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cumulation Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationPercent__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationPercent__c</fullName>
    <label>Cumulation Percent</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultParent__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultParent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sk4_parent__c.sk4_family__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Families</relationshipLabel>
    <relationshipName>Families</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultPocketMoneyAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultPocketMoneyAmount__c</fullName>
    <label>Default PocketMoney Amount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_PocketMoneyDay__c.field-meta.xml
<CustomField>
    <fullName>sk4_PocketMoneyDay__c</fullName>
    <label>PocketMoney Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_ScheduledPocketMoneyEnabled__c.field-meta.xml
<CustomField>
    <fullName>sk4_ScheduledPocketMoneyEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scheduled PocketMoney Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_parent__c/sk4_parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Parents</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_cumulation__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cumulation</label>
    <referenceTo>sk4_cumulation__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_parent__c.field-meta.xml
<CustomField>
    <fullName>sk4_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_type__c.field-meta.xml
<CustomField>
    <fullName>sk4_type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PocketMoney</fullName>
            </value>
            <value>
                <fullName>Cumulation</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/schedule/main/default/classes/sk4_ScheduleBatchTest.cls
@IsTest
public with sharing class sk4_ScheduleBatchTest {
    private static final Integer DEFAULT_PERCENT = 50;
    private static final Integer DEFAULT_POCKETMONEY = 50;
    private static final String USER_NAME = 'TestUser';
    private static final String FAMILY_NAME = 'TestFAMILY';
    @TestSetup
    static void makeData() {
        User u = sk4_TestDataFactory.createSk4rbonkaAdminUser(USER_NAME);

        sk4_family__c family = sk4_TestDataFactory.createFamilies(FAMILY_NAME, 1)[0];
        family.sk4_cumulationDay__c = Date.today().day();
        family.sk4_cumulationPercent__c = 50;
        family.sk4_cumulationEnabled__c = true;
        insert family;

        sk4_parent__c parent = sk4_TestDataFactory.createParent('Jane', family.Id);
        insert parent;

        family.sk4_defaultParent__c = parent.Id;
        family.sk4_ScheduledPocketMoneyEnabled__c = true;
        family.sk4_defaultPocketMoneyAmount__c = DEFAULT_POCKETMONEY;
        family.sk4_pocketMoneyDay__c = Date.today().day();

        update family;

        List<sk4_child__c> children = new List<sk4_child__c>();
        for (Integer i = 0; i < 3; i++) {
            sk4_child__c child = new sk4_child__c();
            child.Name = 'John' + i;
            child.sk4_family__c = family.Id;
            children.add(child);
        }
        insert children;
    }

    @IsTest
    static void testInTheDay() {
        User testUser = [
            SELECT Id
            FROM User
            WHERE LastName = :USER_NAME
        ];
        System.runAs(testUser) {
            Test.startTest();
            Database.executeBatch(new sk4_ScheduleBatch());
            Test.stopTest();
        }
        Integer cumulationNumber = [
            SELECT COUNT()
            FROM sk4_cumulation__c
        ];
        Integer pocketMoneyNumber = [
            SELECT COUNT()
            FROM sk4_transfer__c
            WHERE sk4_type__c = 'PocketMoney'
        ];

        Assert.areEqual(1, cumulationNumber);
        Assert.areEqual(3, pocketMoneyNumber);
    }

    @IsTest
    static void testNotInTheDay() {
        User testUser = [
            SELECT Id
            FROM User
            WHERE LastName = :USER_NAME
        ];
        sk4_family__c family = [
            SELECT Id, sk4_cumulationDay__C
            FROM sk4_family__c
        ];
        family.sk4_cumulationDay__c = Date.today().addDays(1).day();
        family.sk4_pocketMoneyDay__c = Date.today().addDays(1).day();
        update family;

        System.runAs(testUser) {
            Test.startTest();
            Database.executeBatch(new sk4_ScheduleBatch());
            Test.stopTest();
        }
        Integer cumulationNumber = [
            SELECT COUNT()
            FROM sk4_cumulation__c
        ];
        Integer pocketMoneyNumber = [
            SELECT COUNT()
            FROM sk4_transfer__c
            WHERE sk4_type__c = 'PocketMoney'
        ];

        Assert.areEqual(0, cumulationNumber);
        Assert.areEqual(0, pocketMoneyNumber);
    }

    @IsTest
    static void testInTheDayWhenDisabled() {
        User testUser = [
            SELECT Id
            FROM User
            WHERE LastName = :USER_NAME
        ];
        sk4_family__c family = [
            SELECT Id, sk4_cumulationDay__C
            FROM sk4_family__c
        ];
        family.sk4_ScheduledPocketMoneyEnabled__c = false;
        family.sk4_CumulationEnabled__c = false;
        update family;

        System.runAs(testUser) {
            Test.startTest();
            Database.executeBatch(new sk4_ScheduleBatch());
            Test.stopTest();
        }
        Integer cumulationNumber = [
            SELECT COUNT()
            FROM sk4_cumulation__c
        ];
        Integer pocketMoneyNumber = [
            SELECT COUNT()
            FROM sk4_transfer__c
            WHERE sk4_type__c = 'PocketMoney'
        ];

        Assert.areEqual(0, cumulationNumber);
        Assert.areEqual(0, pocketMoneyNumber);
    }
}