src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_date__c.field-meta.xml
<CustomField>
    <fullName>sk4_date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_type__c.field-meta.xml
<CustomField>
    <fullName>sk4_type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PocketMoney</fullName>
            </value>
            <value>
                <fullName>Cumulation</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/soql/main/default/classes/SOQL_Transfer.cls
public inherited sharing class SOQL_Transfer extends SOQL implements SOQL.Selector {
    public static SOQL_Transfer query() {
        return new SOQL_Transfer();
    }

    private SOQL_Transfer() {
        super(sk4_transfer__c.SObjectType);
        with(new List<SObjectField>{ sk4_transfer__c.Id }).systemMode().withoutSharing();
    }

    public SOQL_Transfer byChildId(Id childId) {
        whereAre(Filter.with(sk4_transfer__c.sk4_child__c).equal(childId));
        return this;
    }

    public SOQL_Transfer byTypes(List<String> types) {
        whereAre(Filter.with(sk4_transfer__c.sk4_type__c).isIn(types));
        return this;
    }

    public SOQL_Transfer fromNewest() {
        orderBy(sk4_transfer__c.sk4_date__c);
        return this;
    }
}