src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_amountAfter__c.field-meta.xml
<CustomField>
    <fullName>sk4_amountAfter__c</fullName>
    <label>Amount After</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_date__c.field-meta.xml
<CustomField>
    <fullName>sk4_date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_transferAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_transferAmount__c</fullName>
    <label>Transfer Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_type__c.field-meta.xml
<CustomField>
    <fullName>sk4_type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PocketMoney</fullName>
            </value>
            <value>
                <fullName>Cumulation</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sk4rbonka/main/default/classes/sk4_historyController.cls
public class sk4_HistoryController {

  public static void calculateTotals(Id recordId) {
    List<sk4_transfer__c> originalTransferList = [
      SELECT Id, sk4_type__c, sk4_transferAmount__c, sk4_amountAfter__c
      FROM sk4_transfer__c
      WHERE sk4_child__c = :recordId
      ORDER BY sk4_date__c ASC
    ];
    List<sk4_transfer__c> updatedTransferList = new List<sk4_transfer__c>();
    Decimal runningTotal = 0;

    for (sk4_transfer__c transfer : originalTransferList) {
      if (sk4_Const.PLUS_TRANSFERS.contains(transfer.sk4_type__c)) {
        runningTotal += transfer.sk4_transferAmount__c;
      } else if (sk4_Const.MINUS_TRANSFERS.contains(transfer.sk4_type__c)) {
        runningTotal -= transfer.sk4_transferAmount__c;
      }
      transfer.sk4_amountAfter__c = runningTotal;
      updatedTransferList.add(transfer);
    }

    try {
      update updatedTransferList;
    } catch (DmlException e) {
      throw new DmlException(
        'Oh woe is me, for my attempts to update transfers did fail. Pray tell, what foul magic has cursed my code and made it frail?'
      );
    }
  }
}