src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_balance2__c.field-meta.xml
<CustomField>
    <fullName>sk4_balance2__c</fullName>
    <label>Balance</label>
    <summarizedField>sk4_transfer__c.sk4_transferAmount__c</summarizedField>
    <summaryForeignKey>sk4_transfer__c.sk4_child__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/sk4_parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Parents</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_parent__c.field-meta.xml
<CustomField>
    <fullName>sk4_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_transferAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_transferAmount__c</fullName>
    <label>Transfer Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_type__c.field-meta.xml
<CustomField>
    <fullName>sk4_type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PocketMoney</fullName>
            </value>
            <value>
                <fullName>Cumulation</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sk4rbonka/main/default/classes/sk4_CreateTransferRecordsTest.cls
@IsTest
public with sharing class sk4_CreateTransferRecordsTest {
    private final static String USER_NAME = 'TestUser';
    private final static String FAMILY_NAME = 'TestFamily';
    private final static String CHILDREN0_NAME = 'Null';
    private final static String CHILDREN1_NAME = 'One';
    @TestSetup
    static void makeData() {
        User u = sk4_TestDataFactory.createSk4rbonkaAdminUser(USER_NAME);

        List<sk4_family__c> families = sk4_TestDataFactory.createFamilies(FAMILY_NAME, 2);
        insert families;

        List<sk4_child__c> children0 = sk4_TestDataFactory.createChildren(CHILDREN0_NAME, 2, families[0].Id);
        List<sk4_child__c> children1 = sk4_TestDataFactory.createChildren(CHILDREN1_NAME, 2, families[1].Id);
        insert children0;
        insert children1;

        sk4_parent__c parent0 = sk4_TestDataFactory.createParent(CHILDREN0_NAME, families[0].Id);
        sk4_parent__c parent1 = sk4_TestDataFactory.createParent(CHILDREN1_NAME, families[1].Id);
        insert new List<sk4_parent__c>{ parent0, parent1 };

        sk4_transfer__c savingsTransfer = sk4_TestDataFactory.createStandardTransfer(
            'PocketMoney',
            20,
            children1[1].Id,
            parent1.Id
        );
    }

    @IsTest
    static void testCreateOtherTransferFromFlow() {
        sk4_parent__c parent = [
            SELECT Id, Name, sk4_family__c
            FROM sk4_parent__c
            LIMIT 1
        ];

        sk4_child__c child = [
            SELECT Id, Name
            FROM sk4_child__c
            WHERE sk4_family__c = :parent.sk4_family__c
            LIMIT 1
        ];

        sk4_CreateTransferRecords.FlowInput i1 = new sk4_CreateTransferRecords.FlowInput();
        i1.child = child;
        i1.parent = parent;
        i1.otherAmount = 10;
        i1.description = 'TestDescription';

        List<sk4_CreateTransferRecords.FlowInput> inputs = new List<sk4_CreateTransferRecords.FlowInput>{ i1 };

        User u = [
            SELECT Id
            FROM User
            WHERE LastName = :USER_NAME
        ];

        System.runAs(u) {
            Test.startTest();
            sk4_CreateTransferRecords.createRecords(inputs);
            Test.stopTest();

            List<sk4_transfer__c> transfers = [
                SELECT Id
                FROM sk4_transfer__c
                WHERE sk4_child__c = :child.Id AND sk4_type__c = :sk4_Const.TRANSFER_TYPE_OTHER
            ];

            Assert.areEqual(1, transfers.size());
        }
    }

    @IsTest
    static void testCannotCreateOtherTransferWithoutDescription() {
        sk4_parent__c parent = [
            SELECT Id, Name, sk4_family__c
            FROM sk4_parent__c
            LIMIT 1
        ];

        sk4_child__c child = [
            SELECT Id, Name
            FROM sk4_child__c
            WHERE sk4_family__c = :parent.sk4_family__c
            LIMIT 1
        ];

        sk4_CreateTransferRecords.FlowInput i1 = new sk4_CreateTransferRecords.FlowInput();
        i1.child = child;
        i1.parent = parent;
        i1.otherAmount = 10;

        List<sk4_CreateTransferRecords.FlowInput> inputs = new List<sk4_CreateTransferRecords.FlowInput>{ i1 };

        User u = [
            SELECT Id
            FROM User
            WHERE LastName = :USER_NAME
        ];

        System.runAs(u) {
            Test.startTest();
            try {
                sk4_CreateTransferRecords.createRecords(inputs);
                Assert.fail();
            } catch (Exception ex) {
                Assert.isTrue(ex.getMessage().contains('Description must be set in Other Transfer.'));
            }

            Test.stopTest();
        }
    }

    @IsTest
    static void cantCreateTransferWithParentAndChildFromNotSameFamily() {
        sk4_parent__c parent = [
            SELECT Id, Name, sk4_family__c
            FROM sk4_parent__c
            LIMIT 1
        ];

        sk4_child__c child = [
            SELECT Id, Name
            FROM sk4_child__c
            WHERE sk4_family__c != :parent.sk4_family__c
            LIMIT 1
        ];

        sk4_CreateTransferRecords.FlowInput i1 = new sk4_CreateTransferRecords.FlowInput();
        i1.child = child;
        i1.parent = parent;
        i1.pocketMoneyAmount = 10;

        List<sk4_CreateTransferRecords.FlowInput> inputs = new List<sk4_CreateTransferRecords.FlowInput>{ i1 };

        User u = [
            SELECT Id
            FROM User
            WHERE LastName = :USER_NAME
        ];

        System.runAs(u) {
            Test.startTest();

            try {
                sk4_CreateTransferRecords.createRecords(inputs);
                Assert.fail();
            } catch (Exception ex) {
                Assert.isTrue(ex.getMessage().contains('Child and parent must be from the same family!'));
            }
            Test.stopTest();
        }
    }

    @IsTest
    static void testCanWithdrawMoreMoneyThanOnAccount() {
        sk4_CreateTransferRecords.FlowInput i1 = new sk4_CreateTransferRecords.FlowInput();
        i1.parent = [
            SELECT Id, Name, sk4_family__c
            FROM sk4_parent__c
            LIMIT 1
        ];

        i1.child = [
            SELECT Id, Name
            FROM sk4_child__c
            WHERE sk4_family__c = :i1.parent.sk4_family__c
            LIMIT 1
        ];
        i1.withdrawAmount = 15;

        sk4_transfer__c pocketMoney = sk4_TestDataFactory.createStandardTransfer(
            'PocketMoney',
            10,
            i1.child.Id,
            i1.parent.Id
        );
        pocketMoney.sk4_family__c = i1.parent.sk4_family__c;
        insert pocketMoney;

        List<sk4_CreateTransferRecords.FlowInput> inputs = new List<sk4_CreateTransferRecords.FlowInput>{ i1 };

        User u = [
            SELECT Id
            FROM User
            WHERE LastName = :USER_NAME
        ];

        System.runAs(u) {
            Test.startTest();
            sk4_CreateTransferRecords.createRecords(inputs);
            Test.stopTest();
        }

        sk4_child__c fetchedChild = [
            SELECT Id, sk4_balance2__c
            FROM sk4_child__c
            WHERE Id = :i1.child.Id
        ];

        Assert.areEqual(-5, fetchedChild.sk4_balance2__c);
    }

    @IsTest
    static void createDeductionTransferFromFlow() {
        sk4_CreateTransferRecords.FlowInput i1 = new sk4_CreateTransferRecords.FlowInput();
        i1.parent = [
            SELECT Id, Name, sk4_family__c
            FROM sk4_parent__c
            LIMIT 1
        ];

        i1.child = [
            SELECT Id, Name
            FROM sk4_child__c
            WHERE sk4_family__c = :i1.parent.sk4_family__c
            LIMIT 1
        ];

        i1.deductionAmount = 10;

        List<sk4_CreateTransferRecords.FlowInput> inputs = new List<sk4_CreateTransferRecords.FlowInput>{ i1 };

        User u = [
            SELECT Id
            FROM User
            WHERE LastName = :USER_NAME
        ];

        System.runAs(u) {
            sk4_CreateTransferRecords.createRecords(inputs);
        }

        List<sk4_transfer__c> deductionTransfers = [
            SELECT Id, sk4_type__c, sk4_transferAmount__c
            FROM sk4_transfer__c
            WHERE sk4_type__c = 'Deduction'
        ];

        Assert.areEqual(1, deductionTransfers.size());
        Assert.areEqual(-10, deductionTransfers[0].sk4_transferAmount__c);
    }
}