src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/sk4_cumulation__c.object-meta.xml
<CustomObject>
    <label>Cumulation</label>
    <nameField>
        <displayFormat>CML-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cumulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_cumulationDate__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationDate__c</fullName>
    <label>Cumulation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Cumulations</relationshipLabel>
    <relationshipName>Cumulations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/sk4_parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Parents</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_cumulation__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cumulation</label>
    <referenceTo>sk4_cumulation__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_parent__c.field-meta.xml
<CustomField>
    <fullName>sk4_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_transferAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_transferAmount__c</fullName>
    <label>Transfer Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_type__c.field-meta.xml
<CustomField>
    <fullName>sk4_type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PocketMoney</fullName>
            </value>
            <value>
                <fullName>Cumulation</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/recordTypes/Cumulation.recordType-meta.xml
<RecordType>
    <fullName>Cumulation</fullName>
    <active>true</active>
    <label>Cumulation</label>
</RecordType>

src/sk4rbonka/main/default/objects/sk4_transfer__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

src/sk4rbonka/main/default/classes/sk4_TestDataFactory.cls
public with sharing class sk4_TestDataFactory {
    private static Id STANDARD_TRANSFER_RT_ID = Schema.SObjectType.sk4_transfer__c.getRecordTypeInfosByName()
        .get('Standard')
        .getRecordTypeId();

    public static User createSk4rbonkaAdminUser(String lastName) {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        User u = new User(
            Alias = 'tst',
            Email = 'test@sk4rbon.ka',
            EmailEncodingKey = 'UTF-8',
            LastName = lastName,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'test@sk4rbon.ka'
        );
        insert u;
        PermissionSet ps = [
            SELECT Id
            FROM PermissionSet
            WHERE Name = 'sk4_admin'
        ];

        System.runAs(u) {
            insert new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = ps.Id);
        }

        return u;
    }
    public static User createSk4rbonkaUser(String lastName) {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        User u = new User(
            Alias = 'tst',
            Email = 'testuser@sk4rbon.ka',
            EmailEncodingKey = 'UTF-8',
            LastName = lastName,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = lastName + '@sk4rbon.ka'
        );
        insert u;
        PermissionSet ps = [
            SELECT Id
            FROM PermissionSet
            WHERE Name = 'sk4_user'
        ];

        System.runAs(u) {
            insert new PermissionSetAssignment(AssigneeId = u.Id, PermissionSetId = ps.Id);
        }

        return u;
    }

    public static List<sk4_family__c> createFamilies(String namePrefix, Integer size) {
        List<sk4_family__c> families = new List<sk4_family__c>();
        for (Integer i = 1; i <= size; i++) {
            sk4_family__c family = new sk4_family__c();
            family.Name = namePrefix + i;
            families.add(family);
        }

        return families;
    }

    public static List<sk4_child__c> createChildren(String namePrefix, Integer size, Id familyId) {
        List<sk4_child__c> children = new List<sk4_child__c>();
        for (Integer i = 1; i <= size; i++) {
            sk4_child__c child = new sk4_child__c();
            child.Name = namePrefix + i;
            child.sk4_family__c = familyId;
            children.add(child);
        }
        return children;
    }

    public static sk4_parent__c createParent(String name, Id familyId) {
        sk4_parent__c parent = new sk4_parent__c();
        parent.Name = name;
        parent.sk4_family__c = familyId;
        return parent;
    }

    public static sk4_transfer__c createStandardTransfer(String type, Decimal amount, Id childId, Id parentId) {
        sk4_transfer__c transfer = new sk4_transfer__c();
        transfer.sk4_type__c = type;
        transfer.sk4_transferAmount__c = amount;
        transfer.sk4_child__c = childId;
        transfer.sk4_parent__c = parentId;
        return transfer;
    }

    public static sk4_transfer__c createStandardTransfer(String type, Decimal amount) {
        sk4_transfer__c transfer = new sk4_transfer__c();
        transfer.sk4_type__c = type;
        transfer.sk4_transferAmount__c = amount;
        return transfer;
    }

    public static sk4_cumulation__c createCumulation(Date cumulationDate, Id familyId) {
        sk4_cumulation__c cumulation = new sk4_cumulation__c();
        cumulation.sk4_cumulationDate__c = cumulationDate;
        cumulation.sk4_family__c = familyId;
        return cumulation;
    }
}