src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_balance2__c.field-meta.xml
<CustomField>
    <fullName>sk4_balance2__c</fullName>
    <label>Balance</label>
    <summarizedField>sk4_transfer__c.sk4_transferAmount__c</summarizedField>
    <summaryForeignKey>sk4_transfer__c.sk4_child__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationDay__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationDay__c</fullName>
    <label>Cumulation Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_CumulationEnabled__c.field-meta.xml
<CustomField>
    <fullName>sk4_CumulationEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cumulation Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationPercent__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationPercent__c</fullName>
    <label>Cumulation Percent</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultParent__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultParent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sk4_parent__c.sk4_family__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Families</relationshipLabel>
    <relationshipName>Families</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultPocketMoneyAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultPocketMoneyAmount__c</fullName>
    <label>Default PocketMoney Amount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_PocketMoneyDay__c.field-meta.xml
<CustomField>
    <fullName>sk4_PocketMoneyDay__c</fullName>
    <label>PocketMoney Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_ScheduledPocketMoneyEnabled__c.field-meta.xml
<CustomField>
    <fullName>sk4_ScheduledPocketMoneyEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scheduled PocketMoney Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_parent__c/sk4_parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Parents</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_parent__c.field-meta.xml
<CustomField>
    <fullName>sk4_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_transferAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_transferAmount__c</fullName>
    <label>Transfer Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_type__c.field-meta.xml
<CustomField>
    <fullName>sk4_type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PocketMoney</fullName>
            </value>
            <value>
                <fullName>Cumulation</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/recordTypes/Cumulation.recordType-meta.xml
<RecordType>
    <fullName>Cumulation</fullName>
    <active>true</active>
    <label>Cumulation</label>
</RecordType>

src/sk4rbonka/main/default/classes/sk4_CreateTransfersTest.cls
@IsTest
public with sharing class sk4_CreateTransfersTest {
    private static final String USER_NAME = 'TestUser';
    private static final String FAMILY_NAME = 'TestFamily';
    @TestSetup
    static void makeData() {
        User user = sk4_TestDataFactory.createSk4rbonkaAdminUser(USER_NAME);

        sk4_family__c family = sk4_TestDataFactory.createFamilies(FAMILY_NAME, 1)[0];
        family.sk4_cumulationPercent__c = 50;
        insert family;

        sk4_parent__c parent = sk4_TestDataFactory.createParent('Oneone', family.Id);
        insert parent;

        family.sk4_defaultParent__c = parent.Id;
        family.sk4_ScheduledPocketMoneyEnabled__c = true;
        family.sk4_CumulationEnabled__c = true;
        family.sk4_defaultPocketMoneyAmount__c = 10;
        family.sk4_cumulationDay__c = date.today().day();
        family.sk4_PocketMoneyDay__c = date.today().day();
        update family;

        List<sk4_child__c> children = sk4_TestDataFactory.createChildren('One', 2, family.Id);
        insert children;
    }

    @IsTest
    static void testCreatePocketMoneyTransfer() {
        sk4_family__c family = [SELECT Id, sk4_defaultPocketMoneyAmount__c, sk4_defaultParent__c FROM sk4_family__c];
        Id childId = [SELECT Id FROM sk4_child__c LIMIT 1].Id;

        Test.startTest();
        sk4_transfer__c transfer = sk4_CreateTransfers.createPocketMoneyTransfer(family, childId);
        Test.stopTest();

        Assert.areEqual(10, transfer.sk4_transferAmount__c);
        Assert.areEqual('PocketMoney', transfer.sk4_type__c);
    }

    @IsTest
    static void testCreateCumulationTransfer() {
        sk4_child__c child = [SELECT Id, sk4_family__c, sk4_balance2__c FROM sk4_child__c LIMIT 1];
        Test.startTest();
        sk4_transfer__c transfer = sk4_CreateTransfers.createCumulationTransfer(child);
        Test.stopTest();

        Assert.areEqual(0, transfer.sk4_transferAmount__c);
        Assert.areEqual('Cumulation', transfer.sk4_type__c);
    }

    @IsTest
    static void addTransfer() {
        Id childId = [SELECT Id FROM sk4_child__c LIMIT 1].Id;

        sk4_CreateTransfers.addWithdraw(childId, 10, 'PocketMoney', 'description');

        Test.startTest();
        sk4_transfer__c transfer = [SELECT id, sk4_transferAmount__c, sk4_child__c FROM sk4_transfer__c];
        Test.stopTest();

        Assert.isNotNull(transfer);
        Assert.areEqual(10, transfer.sk4_transferAmount__c);
        Assert.areEqual(childId, transfer.sk4_child__c);

    }
}