src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_balance2__c.field-meta.xml
<CustomField>
    <fullName>sk4_balance2__c</fullName>
    <label>Balance</label>
    <summarizedField>sk4_transfer__c.sk4_transferAmount__c</summarizedField>
    <summaryForeignKey>sk4_transfer__c.sk4_child__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/sk4_cumulation__c.object-meta.xml
<CustomObject>
    <label>Cumulation</label>
    <nameField>
        <displayFormat>CML-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cumulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_cumulationMonth__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationMonth__c</fullName>
    <formula>MONTH(sk4_cumulationDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cumulation Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_cumulationYear__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationYear__c</fullName>
    <formula>YEAR(sk4_cumulationDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cumulation Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_cumulation__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Cumulations</relationshipLabel>
    <relationshipName>Cumulations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationLowerTreshold__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationLowerTreshold__c</fullName>
    <label>Cumulation Lower Treshold</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationPercent__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationPercent__c</fullName>
    <label>Cumulation Percent</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_cumulationUpperTreshold__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulationUpperTreshold__c</fullName>
    <label>Cumulation Upper Treshold</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_cumulation__c.field-meta.xml
<CustomField>
    <fullName>sk4_cumulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cumulation</label>
    <referenceTo>sk4_cumulation__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/recordTypes/Cumulation.recordType-meta.xml
<RecordType>
    <fullName>Cumulation</fullName>
    <active>true</active>
    <label>Cumulation</label>
</RecordType>

src/sk4rbonka/main/default/classes/sk4_CumulateTriggerHandler.cls
public with sharing class sk4_CumulateTriggerHandler {
    public static void beforeInsert(List<sk4_cumulation__c> cumulations) {
        checkIsCumulationInCurrentMonth(cumulations);
    }

    public static void beforeUpdate(List<sk4_cumulation__c> cumulations) {
        preventUpdating(cumulations);
    }

    public static void beforeDelete(Map<Id, sk4_cumulation__c> cumulations) {
        deleteTransfers(cumulations.keySet());
    }

    public static void afterInsert(List<sk4_cumulation__c> cumulations) {
        createCumulationTransfers(cumulations);
    }

    private static void deleteTransfers(Set<Id> cumulationIds) {
        delete SOQL_Transfer.query().byCumulationIds(cumulationIds).toList();
    }

    private static void preventUpdating(List<sk4_cumulation__c> cumulations) {
        for (sk4_cumulation__c c : cumulations) {
            c.addError('Editing is not allowed. Delete cumulation and create new one.');
        }
    }

    private static void createCumulationTransfers(List<sk4_cumulation__c> cumulations) {
        List<sk4_transfer__c> transfers = new List<sk4_transfer__c>();
        Map<Id, sk4_cumulation__c> familyToCumulation = new Map<Id, sk4_cumulation__c>();

        for (sk4_cumulation__c c : cumulations) {
            familyToCumulation.put(c.sk4_family__c, c);
        }

        List<sk4_child__c> children = SOQL_Child.query()
            .byFamilyIds(familyToCumulation.keySet())
            .with(sk4_child__c.sk4_balance2__c, sk4_child__c.sk4_family__c)
            .with(
                'sk4_family__r',
                new List<SObjectField>{
                    sk4_family__c.sk4_cumulationPercent__c,
                    sk4_family__c.sk4_cumulationUpperTreshold__c,
                    sk4_family__c.sk4_cumulationLowerTreshold__c
                }
            )
            .preview()
            .toList();

        for (sk4_child__c child : children) {
            sk4_transfer__c transfer = sk4_CreateTransfers.createCumulationTransfer(child) ;
            transfer.sk4_cumulation__c = familyToCumulation.get(child.sk4_family__c).Id;
            transfers.add(transfer);
        }

        insert transfers;
    }

    private static void checkIsCumulationInCurrentMonth(List<sk4_cumulation__c> cumulations) {
        Map<Id, List<sk4_cumulation__c>> familyToCumulation = new Map<Id, List<sk4_cumulation__c>>();

        for (sk4_cumulation__c c : (List<sk4_cumulation__c>) SOQL_Cumulation.query().toList()) {
            List<sk4_cumulation__c> familiesCumuls = new List<sk4_cumulation__c>();
            if (familyToCumulation.get(c.sk4_family__c) != null) {
                familiesCumuls = familyToCumulation.get(c.sk4_family__c);
            }
            familiesCumuls.add(c);
            familyToCumulation.put(c.sk4_family__c, familiesCumuls);
        }

        for (sk4_cumulation__c c : cumulations) {
            List<sk4_cumulation__c> relatedCumuls = familyToCumulation.get(c.sk4_family__c);

            if (relatedCumuls != null) {
                for (sk4_cumulation__c relC : relatedCumuls) {
                    if (
                        c.sk4_cumulationMonth__c == relC.sk4_cumulationMonth__c &&
                        c.sk4_cumulationYear__c == relC.sk4_cumulationYear__c
                    ) {
                        c.addError('You cannot perform two cumulations per month!');
                    }
                }
            }
        }
    }
}