src/sk4rbonka/main/default/objects/sk4_child__c/sk4_child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_child__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_family__c/sk4_family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_family__c/fields/sk4_defaultParent__c.field-meta.xml
<CustomField>
    <fullName>sk4_defaultParent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sk4_parent__c.sk4_family__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Families</relationshipLabel>
    <relationshipName>Families</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_parent__c/sk4_parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_parent__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Parents</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/sk4_transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_child__c.field-meta.xml
<CustomField>
    <fullName>sk4_child__c</fullName>
    <label>Child</label>
    <referenceTo>sk4_child__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_description__c.field-meta.xml
<CustomField>
    <fullName>sk4_description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_family__c.field-meta.xml
<CustomField>
    <fullName>sk4_family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>sk4_family__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_parent__c.field-meta.xml
<CustomField>
    <fullName>sk4_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>sk4_parent__c</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_transferAmount__c.field-meta.xml
<CustomField>
    <fullName>sk4_transferAmount__c</fullName>
    <label>Transfer Amount</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sk4rbonka/main/default/objects/sk4_transfer__c/fields/sk4_type__c.field-meta.xml
<CustomField>
    <fullName>sk4_type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PocketMoney</fullName>
            </value>
            <value>
                <fullName>Cumulation</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sk4rbonka/main/default/classes/sk4_CreateTransfers.cls
public with sharing class sk4_CreateTransfers {
    private static Id getDefaultParentId(Id childId) {
        sk4_child__c child = (sk4_child__c) SOQL_Child.query().byId(childId).preview().toObject();
        return child.sk4_family__r.sk4_defaultParent__c;

    }

    private static String getRecordTypeId(String type) {
        return sk4_Const.TYPE_TO_RT_ID.get(type);
    }

    public static void addWithdraw(Id childId, Decimal amount, String type, String description) {
        Id parentId = (Id) SOQL_Parent.query().byCurrentUser().toValueOf(sk4_parent__c.Id);
        sk4_parent__c parent = (sk4_parent__c) SOQL_Parent.query().byId(parentId).toObject();
        if (parentId == null) {
            parentId = getDefaultParentId(childId);
        }

        if (parentId == null) {
            throw new TransferException('Default Parent is not set!');
        }

        sk4_Transfer__c transfer = new sk4_transfer__c();
        transfer.sk4_child__c = childId;
        transfer.sk4_description__c = description;
        transfer.sk4_family__c = parent.sk4_family__c;
        transfer.sk4_parent__c = parentId;
        transfer.sk4_transferAmount__c = sk4_Const.MINUS_TRANSFERS.contains(type) ? amount * -1 : amount ;
        transfer.sk4_type__c = type;
        transfer.RecordTypeId = getRecordTypeId(type);

        insert transfer;

    }
}